config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "/dashboard", to: "pages#dashboard", as: "dashboard"

  resources :listings do
    put "/next_status" => "listings#next_status"
    put "/prev_status" => "listings#prev_status"
  end
  resources :technologies
  resources :companies

  root "pages#index"
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  belongs_to :company

  has_many :requirements, dependent: :destroy
  has_many :technologies, -> { distinct }, through: :requirements

  validates :title, length: { minimum: 3 }
  validates :url, allow_blank: true, format: URI::regexp(%w(http https))

  enum status: { not_applied: 0, applied: 1, called: 2, offered: 3, unsuccessful: 5 }

  def next_status
    case self.status
    when "not_applied"
      self.update(status: "applied")
    when "applied"
      self.update(status: "called")
    when "called"
      self.update(status: "offered")
    when "offered"
      self.update(status: "unsuccessful")
    when "unsuccessful"
      self.update(status: "not_applied")
    end
  end

  def prev_status
    case self.status
    when "not_applied"
      self.update(status: "unsuccessful")
    when "applied"
      self.update(status: "not_applied")
    when "called"
      self.update(status: "applied")
    when "offered"
      self.update(status: "called")
    when "unsuccessful"
      self.update(status: "offered")
    end
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :authenticate_user!

  def index
    @listings = current_user.listings.includes(:technologies, :requirements, :company)
  end

  def show
    @listing = current_user.listings.find(params[:id])
  end

  def edit
    @listing = current_user.listings.find(params[:id])
    @companies = current_user.companies.all
  end

  def update
    @listing = current_user.listings.find(params[:id])

    if @listing.update(listing_params)
      redirect_to @listing, notice: "Listing updated"
    else
      render :edit
    end
  end

  def new
    @listing = current_user.listings.new
  end

  def create
    @listing = current_user.listings.new(listing_params)

    if @listing.save
      redirect_to @listing, notice: "Listing created"
    else
      # Re-render companies in case of errors
      @companies = current_user.companies
      render :new
    end
  end

  def destroy
    @listing = current_user.listings.find(params[:id])
    @listing.destroy
    redirect_to listings_path, notice: "Listing deleted"
  end

  def next_status
    @listing = current_user.listings.find(params[:listing_id])
    @listing.next_status

    respond_to do |format|
      format.js { render template: "listings/kanban_status_change.js.erb", layout: false }
    end
  end

  def prev_status
    @listing = current_user.listings.find(params[:listing_id])
    @listing.prev_status

    respond_to do |format|
      format.js { render template: "listings/kanban_status_change.js.erb", layout: false }
    end
  end

  private

  def listing_params
    params.require(:listing).permit(:title, :company_id, :description, :url, :status, technology_ids: [])
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
  def technologies_to_link_string(listing)
    listing.requirements.map { |r| link_to r.technology.name, r.technology }.join(", ").html_safe
  end
end

app/views/listings/_form.html.erb
<%= render "shared/errors", object: @listing %>

<%= form_with model: @listing, local: true, remote: true do |f| %>
  <div class="form-group">
    <%= f.label "Title" %>
    <%= f.text_field :title , class: "form-control"%>
  </div>

  <div class="form-group">
    <%= f.label "Link (optional)" %>
    <%= f.text_field :url , class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "Company / Location" %>
    <%= collection_select(:listing, :company_id, current_user.companies, :id, :name, { prompt: true }, { required: true, class: 'selectize'}) %>
  </div>

  <div class="form-group">
    <%= f.label "Technologies Required / Desired" %>
    <%= f.collection_select(:technology_ids, current_user.technologies, :id, :name,
			{ prompt: true, include_blank: false, include_hidden: false }, 
			{ required: false, class: 'selectize', multiple: true}) %>
  </div>

  <div class="form-group">
    <%= f.label "Status" %>
    <%= f.select :status, Listing.statuses.keys.map {|s| [s.humanize.capitalize, s] }, {}, { class: 'form-control' } %>
  </div>

  <div class="form-group">
    <%= f.label "Description" %>
    <%= f.text_area :description , class: "form-control", rows: 10%>
  </div>
  <%= f.submit class: 'btn btn-outline-primary btn-block btn-large' %>
<% end %>

app/views/listings/_kanban.html.erb
<div class="container-fluid kanban-board">
  <div class="row flex-row flex-sm-nowrap py-4">
    <div class="col-sm-12 col-md-5 col-lg-4 col-xl mb-3">
      <div id="not_applied-col" class="card bg-light">
        <div class="card-block p-3">
          <h4 class="card-title text-secondary text-center py-2">Not Applied</h4>
          <% @listings.not_applied.each do |listing| %>
            <%= render 'listings/kanban_card', listing: listing %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-sm-12 col-md-5 col-lg-4 col-xl mb-3">
      <div id="applied-col" class="card bg-light">
        <div class="card-block p-3">
          <h4 class="card-title text-info text-center py-2">Applied</h4>
          <% @listings.applied.each do |listing| %>
            <%= render 'listings/kanban_card', listing: listing %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-sm-12 col-md-5 col-lg-4 col-xl mb-3">
      <div id="called-col" class="card bg-light">
        <div class="card-block p-3">
          <h4 class="card-title text-primary text-center py-2">Called</h4>
          <% @listings.called.each do |listing| %>
            <%= render 'listings/kanban_card', listing: listing %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-sm-12 col-md-5 col-lg-4 col-xl mb-3">
      <div id="offered-col" class="card bg-light">
        <div class="card-block p-3">
          <h4 class="card-title text-success text-center py-2">Offered</h4>
          <% @listings.offered.each do |listing| %>
            <%= render 'listings/kanban_card', listing: listing %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-sm-12 col-md-5 col-lg-4 col-xl">
      <div id="unsuccessful-col" class="card bg-light">
        <div class="card-block p-3">
          <h4 class="card-title text-danger text-center py-2">Unsuccessful</h4>
          <% @listings.unsuccessful.each do |listing| %>
            <%= render 'listings/kanban_card', listing: listing %>
          <% end %>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/listings/_kanban_card.html.erb
<div id='<%= "listing-#{listing.id}" %>' class="card p-2 my-2">
  <h6 class="card-title mb-1">
    <%= link_to listing do %>
      <%= listing.title %> at <span class="text-muted"><%= listing.company.name %></span>
    <% end %>
  </h6>

  <p class="mb-1">
    <% listing.technologies.each do |tech| %>
      <span class="badge badge-pill badge-light"><%= tech.name %> </span>
    <% end %>
  </p>

  <div class="d-flex justify-content-between card-status-actions">
    <% if listing.not_applied? %>
      <i></i>
    <% else %>
      <%= link_to listing_prev_status_path(listing), method: :put, remote: true, class: "listing-#{listing.id}-prev-status" do %>
        <i class="fas fa-arrow-left"></i>
      <% end %>
    <% end %>

    <% if listing.unsuccessful? %>
      <i></i>
    <% else %>
      <%= link_to listing_next_status_path(listing), method: :put, remote: true, class: "listing-#{listing.id}-next-status" do %>
        <i class="fas fa-arrow-right"></i>
      <% end %>
    <% end %>
  </div>
</div>

app/views/listings/_table.html.erb
<div class="container-fluid">
  <%- if @listings.empty? %>
    <p>You don't have any listings at this moment...</p>
  <% else %>
    <div class="table-responsive">
      <table class="table">
        <thead>
          <thead>
            <tr>
              <th scope="col">Status</th>
              <th scope="col">Title</th>
              <th scope="col">Company</th>
              <th scope="col">Description</th>
              <th scope="col">Technologies</th>
            </tr>
          </thead>
        </thead>
        <tbody>
          <% @listings.each_with_index do |listing, i| %>
            <tr>
              <td><%= get_status(listing) %></td>
              <td><%= link_to listing.title, listing %></td>
              <td><%= listing.company.name %></td>
              <td><%= truncate(listing.description, length: 25, separator: ' ') %></td>
              <td>
                <%= technologies_to_link_string(listing) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
</div>

app/views/listings/edit.html.erb
<div class="listing-form m-auto">
	<h1 class="my-4">Edit listing</h1>
	
	<%= render 'form' %>
</div>

app/views/listings/index.html.erb
<div class="mx-auto">
  <!-- <h2 class="my-4 text-center">Your Listings</h2> -->

  <ul class="nav nav-pills justify-content-center" id="myTab" role="tablist">
    <li class="nav-item">
      <a class="nav-link" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="false">Table</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="true">Kanban</a>
    </li>
  </ul>
  <div class="tab-content" id="myTabContent">
    <div class="tab-pane fade" id="home" role="tabpanel" aria-labelledby="home-tab">
      <div class="break-out">
        <%= render 'listings/table', listings: @listings %>
      </div>
    </div>
    <div class="tab-pane fade show active" id="profile" role="tabpanel" aria-labelledby="profile-tab">
      <div class="break-out">
        <%= render 'listings/kanban', listings: @listings %>
      </div>
    </div>
  </div>

</div>

app/views/listings/kanban_status_change.js.erb
<% if @listing.errors.any? %>
  console.log("Some error occurred. Could not update listing...");
<% else %>
  $('<%= "#listing-#{@listing.id}" %>').remove()
  $('<%= "##{@listing.status}-col .card-block" %>').append(
  "<%= escape_javascript(render partial: 'listings/kanban_card', locals: { listing: @listing }) %>")
<% end %>

app/views/listings/new.html.erb
<div class="listing-form m-auto">
	<h1 class="my-4">Create a new listing</h1>
	
	<%= render 'form' %>
</div>

app/views/listings/show.html.erb
<h2 class="display-3  my-4">
  <%= @listing.title %>
</h2>

<h3>
  <%= link_to @listing.company.name, @listing.company %>
  <span class="text-muted pl-4"> <%= display_rating(@listing.company) %> </span>
</h3>
<h3 class="mb-4">
  <%= get_status(@listing) %>
</h3>

<div class="row">
  <div class="col-8">
    <article class="py-2 mt-3">
      <%= link_to 'Go to listing', url_for(@listing.url) %>
      <p><%= @listing.description %></p>
    </article>
  </div>

  <div class="col-4">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Requirements</h5>

        <ul>
          <% @listing.requirements.each do |req| %>
            <li><%= link_to req.technology.name, req.technology, class: 'card-link'%></li>
          <% end %>
        </ul>
      </div>
    </div>

  </div>
</div>

<div class="mt-5">
  <%= link_to 'Edit', edit_listing_path(@listing), class: 'btn btn-outline-primary' %>

  <%= link_to 'Delete', @listing, method: :delete, class: 'btn btn-danger btn-large', data: { confirm: 'Are you sure?' } %>
</div>