config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "/dashboard", to: "pages#dashboard", as: "dashboard"

  resources :listings do
    put "/next_status" => "listings#next_status"
    put "/prev_status" => "listings#prev_status"
  end
  resources :technologies
  resources :companies

  root "pages#index"
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user
  has_many :listings, dependent: :destroy

  validates :name, length: { minimum: 2 }, uniqueness: true
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!

  def index
    @companies = current_user.companies.all
  end

  def show
    @company = current_user.companies.find(params[:id])
    @company_tech = Technology.joins(:listings).where(listings: { company_id: @company.id })
    Scraper.update_rating(@company, "Vancouver")
  end

  def new
    @company = current_user.companies.new
  end

  def create
    @company = current_user.companies.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: "Company created" }
        format.json { render json: { value: @company.id, text: @company.name } }
      else
        format.html { render :new }
        format.json { render json: { errors: @company.errors.full_messages } }
      end

      # Handle very fast tab insertions on form
    rescue ActiveRecord::RecordNotUnique
      format.json { render json: { message: "Company already created" } }
    end
  end

  def edit
    @company = current_user.companies.find(params[:id])
  end

  def update
    @company = current_user.companies.find(params[:id])

    if @company.update(company_params)
      redirect_to @company, notice: "Company updated"
    else
      render :edit
    end
  end

  def destroy
    @company = current_user.companies.find(params[:id])
    @company.destroy
    redirect_to companies_path, notice: "Company deleted"
  end

  private

  def company_params
    params.require(:company).permit(:name, :address, :user_glassdoor_rate)
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for @company do |f| %>
  <%= render 'shared/errors', object: @company %>
  <div class="form-group">
    <%= f.label 'Name' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label 'Office Address' %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>

  <% if @company.persisted? %>
    <div class="form-group">
      <%= f.label 'Company Rating (overrides automatic rating)' %>
      <%= f.text_field :user_glassdoor_rate, class: 'form-control' %>
    </div>
  <% end %>
  <%= f.submit class: 'btn btn-block btn-outline-primary' %>
<% end %>

app/views/companies/create.js.erb
$('#listing_company_id').html("<%= escape_javascript collection_select(:listing, :company_id, @companies, :id, :name, { prompt: true }, { required: true, class: 'selectize'}) %>");

app/views/companies/edit.html.erb
<div class="auth-card m-auto">
  <h1 class="my-4">Edit company</h1>
  <%= render 'companies/form' %>
</div>

app/views/companies/index.html.erb
<div class="tech-table mx-auto">
  <!-- <h2 class="my-4">Your Companies</h2> -->
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th class="d-none d-md-table-cell" scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @companies.each do |company| %>
        <tr>
          <td><%= link_to company.name, company %></td>
          <td class="d-none d-md-table-cell">
            <%= link_to 'Edit', edit_company_path(company), class: 'btn btn-sm btn-outline-primary' %>
            <%= link_to 'Delete', company_path(company), method: :delete, class: 'btn btn-sm btn-outline-danger', data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/companies/new.html.erb
<div class="auth-card m-auto">
  <h1 class="my-4">Add a company</h1>
  <%= render 'companies/form' %>
</div>

app/views/companies/show.html.erb
<p class="display-4 font-weight-bold">
  <%= @company.name %>
  <%= link_to 'Edit', edit_company_path(@company), class: 'btn btn-sm btn-outline-primary ml-5 d-none d-md-inline-block' %>
  <%= link_to 'Delete', company_path(@company), method: :delete, class: 'btn btn-sm btn-outline-danger d-none d-md-inline-block', data: { confirm: 'Are you sure?' } %>
</p>
<div class="row">
  <div class="col-4-sm">
    <div class="card mx-auto mt-md-4">
      <% if @company.address.present? %>
        <iframe width="400" height="400" frameborder="1" style="border:0" class="card-img-top"
			src="https://www.google.com/maps/embed/v1/search?q=<%= @company.address.gsub(" ", "+") %>&key=<%= Rails.application.credentials.google[:maps_key] %>" allowfullscreen></iframe>
      <% else %>
        <%= image_tag 'map-placeholder.png', class: 'card-img-top company-map-placeholder',  width: "200" %>
      <% end %>

      <div class="card-body">
        <h4 class="card-text p-0 mb-4"><span class="font-weight-bold">Address:</span> <%= @company.address %></h4>
        <h4 class="card-text p-0 font-weight-bold">Rating: <%= display_rating(@company) %></h4>
      </div>
    </div>
  </div>

  <div class="col-8-sm">
    <div class="m-3 m-md-5">
      <h3 class="mb-4">Listings</h3>
      <% if @company.listings.count < 1 %>
        <p>There are no active listings by <%= @company.name %> at this moment.</p>
      <% else %>
        <ul>
          <% @company.listings.each do |listing| %>
            <li><%= link_to listing.title, listing %></li>
          <% end %>
        </ul>
      <% end %>
    </div>

    <div class="m-3 m-md-5">
      <h3 class="mb-4">Technologies</h3>
      <% if @company_tech.count < 1 %>
        <p>There are no active listings by <%= @company.name %> at this moment.</p>
      <% else %>
        <ul>
          <% @company_tech.each do |tech| %>
            <li><%= link_to tech.name, tech %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>
</div>

<div class="d-block d-md-none text-center">
  <%= link_to 'Edit', edit_company_path(@company), class: 'btn btn-sm btn-outline-primary' %>
  <%= link_to 'Delete', company_path(@company), method: :delete, class: 'btn btn-sm btn-outline-danger', data: { confirm: 'Are you sure?' } %>
</div>