config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "/dashboard", to: "pages#dashboard", as: "dashboard"

  resources :listings do
    put "/next_status" => "listings#next_status"
    put "/prev_status" => "listings#prev_status"
  end
  resources :technologies
  resources :companies

  root "pages#index"
end

app/models/technology.rb
class Technology < ApplicationRecord
  belongs_to :user

  has_many :requirements, dependent: :destroy
  has_many :listings, -> { distinct }, through: :requirements

  validates :name, length: { minimum: 1 }
end

app/controllers/technologies_controller.rb
class TechnologiesController < ApplicationController
  before_action :authenticate_user!

  def index
    @technologies = current_user.technologies
  end

  def show
    @technology = current_user.technologies.find(params[:id])
    @technology_companies = Listing.joins(:requirements).where(requirements: { technology_id: @technology.id }).select(:company_id).distinct
  end

  def new
    @technology = current_user.technologies.new
  end

  def create
    @technology = current_user.technologies.new(tech_params)

    respond_to do |format|
      if @technology.save
        format.html { redirect_to @technology, notice: "Technology created" }
        format.json { render json: { value: @technology.id, text: @technology.name } }
      else
        format.html { render :new }
        format.json { render json: { errors: @technology.errors.full_messages } }
      end

      # Handle very fast tab insertions on form
    rescue ActiveRecord::RecordNotUnique
      format.json { render json: { message: "Technology already created" } }
    end
  end

  def edit
    @technology = current_user.technologies.find(params[:id])
  end

  def update
    @technology = current_user.technologies.find(params[:id])
    if @technology.update(tech_params)
      redirect_to @technology, notice: "Technology updated"
    else
      render :edit
    end
  end

  def destroy
    @technology = current_user.technologies.find(params[:id])
    @technology.destroy
    redirect_to technologies_path, notice: "Technology deleted"
  end

  private

  def tech_params
    params.require(:technology).permit(:name)
  end
end

app/views/technologies/_form.html.erb
<%= form_for @technology do |f| %>
	<%= render "shared/errors", object: @technology %>

	<div class="form-group">
		<%= f.label 'Name' %>
		<%= f.text_field :name, class: 'form-control' %>
	</div>

	<%= f.submit class: 'btn btn-outline-primary btn-block' %>
<% end %>

app/views/technologies/edit.html.erb
<div class="auth-card m-auto">
	<h1 class="my-4">Edit technology</h1>

	<%= render 'technologies/form' %>
</div>

app/views/technologies/index.html.erb
<div class="tech-table mx-auto">
  <!-- <h2 class="my-4">Your Technologies</h2> -->
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Count</th>
        <th class="d-none d-md-table-cell" scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @technologies.each do |tech| %>
        <tr>
          <td><%= link_to truncate(tech.name, length: 40), tech %></td>
          <td>
            <span class="badge badge-pill badge-primary">
              <%= tech.requirements.size %>
            </span>
          </td>
          <td class="d-none d-md-table-cell">
            <%= link_to 'Edit', edit_technology_path(tech), class: 'btn btn-sm btn-outline-primary' %>
            <%= link_to 'Delete', technology_path(tech), method: :delete, class: 'btn btn-sm btn-outline-danger', data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/technologies/new.html.erb
<div class="auth-card m-auto">
	<h1 class="my-4">Add a technology</h1>

	<%= render 'technologies/form' %>
</div>

app/views/technologies/show.html.erb
<div class="tech-show mx-auto">
  <p class="display-4 font-weight-bold">
    <%= @technology.name %>
    <%= link_to 'Edit', edit_technology_path(@technology), class: 'btn btn-sm btn-outline-primary ml-5 d-none d-md-inline-block' %>
    <%= link_to 'Delete', technology_path(@technology), method: :delete, class: 'btn btn-sm btn-outline-danger d-none d-md-inline-block', data: { confirm: 'Are you sure?' } %>
  </p>

  <div class="my-5">
    <h3 class="mb-4">Appears on <%= pluralize @technology.requirements.size, 'listing' %>:</h3>
    <% if @technology.listings.size < 1 %>
      <p>There are no active listings requiring <%= @technology.name %> at this moment.</p>
    <% else %>
      <ul>
        <% @technology.listings.each do |listing| %>
          <li><%= link_to listing.title, listing %></li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <div class="my-5">
    <h3 class="mb-4">Used by:</h3>
    <% if @technology_companies.size < 1 %>
      <p>There are no active listings requiring <%= @technology.name %> at this moment.</p>
    <% else %>
      <ul>
        <% @technology_companies.each do |listing| %>
          <li>
            <%= link_to listing.company.name, listing.company %>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <div class="d-block d-md-none text-center">
    <%= link_to 'Edit', edit_technology_path(@technology), class: 'btn btn-sm btn-outline-primary' %>
    <%= link_to 'Delete', technology_path(@technology), method: :delete, class: 'btn btn-sm btn-outline-danger', data: { confirm: 'Are you sure?' } %>
  </div>
</div>