config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "/dashboard", to: "pages#dashboard", as: "dashboard"

  resources :listings do
    put "/next_status" => "listings#next_status"
    put "/prev_status" => "listings#prev_status"
  end
  resources :technologies
  resources :companies

  root "pages#index"
end

app/views/layouts/_action_menu.html.erb
<div class="bg-light mb-4">
  <div class="container">
    <ul class="nav justify-content-center">
      <li class="nav-item">
        <%= nav_link 'Dashboard', dashboard_path %>
      </li>
      <li class="nav-item">
        <%= nav_link 'Listings', listings_path %>
      </li>
      <li class="nav-item">
        <%= nav_link 'Technologies', technologies_path %>
      </li>
      <li class="nav-item">
      </li>
      <li class="nav-item">
        <%= nav_link 'Companies', companies_path %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><i class="fas fa-plus-circle"></i> New</a>
        <div class="dropdown-menu">
          <%= link_to 'New Listing', new_listing_path, class: 'dropdown-item' %>
          <%= link_to 'New Technology', new_technology_path, class: 'dropdown-item' %>
          <%= link_to 'New Company', new_company_path, class: 'dropdown-item' %>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/_flash_messages.html.erb
<div class="alert-float">
  <%- if notice %>
    <div class="alert alert-success p-3" role="alert">
      <span class="mr-3"><%= notice %></span>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <%- elsif alert %>
    <div class="alert alert-danger" role="alert">
      <span><%= alert %></span>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<div class="break-out bg-dark text-light links-light footer ">
	<footer class="container py-4 py-md-5">
		<div class="row">
			<div class="col-12 order-2 order-md-1 text-center text-md-left col-md my-auto">
				<%= image_tag 'logo-for-dark-bg.png', class: 'img-fluid w-75', height: "20px" %>
				<p class="mt-1">
				built by <%= link_to "hugocbp.com", "https://hugocbp.com" %> | © <%= Date.today.year %>
				</p>
				
			</div>
			<div class="col-12 order-md-2 offset-lg-1 col-md d-none d-md-block">
				<h5>Features</h5>
				<ul class="list-unstyled text-small">
					<li><a class="text-muted" href="#summary">Summary</a></li>
					<li><a class="text-muted" href="#dashboard">Dashboard</a></li>
					<li><a class="text-muted" href="#kanban">Kanban</a></li>
					<li><a class="text-muted" href="#company">Company Info</a></li>
				</ul>
			</div>
			<div class="col-12 order-1 order-md-3 col-md text-center text-md-left">
				<h5>About</h5>
				<ul class="list-unstyled text-small">
					<li><a class="text-muted" href="#">Contact</a></li>
					<li><a class="text-muted" href="#">Contribute</a></li>
					<li><a class="text-muted" href="#">Privacy</a></li>
					<li><a class="text-muted" href="#">Terms</a></li>
				</ul>
			</div>
		</div>
	</footer>
</div>

app/views/layouts/_google_analytics.html.erb
<% if Rails.env.production? && on_heroku? %>
  <script async src="https://www.googletagmanager.com/gtag/js?id=<%= Rails.application.credentials.google[:analytics_key] %>"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    
    gtag('config', '<%= Rails.application.credentials.google[:analytics_key] %>');
  </script>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container">
    <%= link_to root_path, class: 'navbar-left' do %>
      <%= image_tag 'logo-for-dark-bg.png', height: '30px' %>
    <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
      </ul>
      <ul class="navbar-nav text-center">
        <%- if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link active dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_user.email %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to 'Account Settings', edit_user_registration_path, class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Log In', new_user_session_path, class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link active" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Job Hunt Assistant</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/google_analytics' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="<%= yield (:body_class) %>">
    <%= render 'layouts/navbar' %>

    <% if current_user %>
      <%= render 'layouts/action_menu' %>
    <% end %>

    <%= render 'layouts/flash_messages' %>

    <main class="container">
      <%= yield %>
    </main>

    <%= render 'layouts/footer' unless current_user %>

  </body>
</html>